<?php
/** Package Detail ACF field registration. */
function luxxo_register_package_detail_fields() {
    if ( ! function_exists( 'acf_add_local_field_group' ) ) return;
    $text = function( $key, $name, $label ) { return array( 'key' => $key, 'label' => $label, 'name' => $name, 'type' => 'text' ); };
    acf_add_local_field_group( array( 'key' => 'group_luxxo_package_detail', 'title' => 'Package Detail', 'fields' => array(
        array( 'key' => 'field_package_basic_tab', 'label' => 'Package Basic Information', 'type' => 'tab' ), $text( 'field_package_title', 'package_title', 'Package title' ), array( 'key' => 'field_package_short_description', 'label' => 'Short description', 'name' => 'package_short_description', 'type' => 'textarea', 'rows' => 3 ), array( 'key' => 'field_package_hero_image', 'label' => 'Hero image', 'name' => 'package_hero_image', 'type' => 'image', 'return_format' => 'id' ), $text( 'field_package_duration', 'package_duration', 'Duration' ), $text( 'field_package_destinations', 'package_destinations', 'Destinations' ), $text( 'field_package_category', 'package_category', 'Category' ),
        array( 'key' => 'field_package_experience_tab', 'label' => 'Experience', 'type' => 'tab' ), $text( 'field_package_experience_title', 'package_experience_title', 'Experience heading' ), array( 'key' => 'field_package_experience_content', 'label' => 'Experience content', 'name' => 'package_experience_content', 'type' => 'wysiwyg', 'tabs' => 'all', 'media_upload' => 1 ),
        array( 'key' => 'field_package_itinerary_tab', 'label' => 'Itinerary', 'type' => 'tab' ), array( 'key' => 'field_package_itinerary', 'label' => 'Day by day itinerary', 'name' => 'package_itinerary', 'type' => 'repeater', 'layout' => 'block', 'button_label' => 'Add day', 'sub_fields' => array( $text( 'field_package_day_number', 'day_number', 'Day number' ), $text( 'field_package_day_title', 'day_title', 'Day title' ), array( 'key' => 'field_package_day_description', 'label' => 'Description', 'name' => 'day_description', 'type' => 'textarea', 'rows' => 5 ), array( 'key' => 'field_package_day_image', 'label' => 'Image', 'name' => 'day_image', 'type' => 'image', 'return_format' => 'id' ), $text( 'field_package_day_location', 'optional_location', 'Location (optional)' ), $text( 'field_package_day_label', 'optional_label', 'Small label (optional)' ) ) ),
        array( 'key' => 'field_package_inclusions_tab', 'label' => 'Inclusions', 'type' => 'tab' ), array( 'key' => 'field_package_included', 'label' => "What's included", 'name' => 'package_included', 'type' => 'repeater', 'layout' => 'table', 'button_label' => 'Add included item', 'sub_fields' => array( $text( 'field_package_included_item', 'item', 'Item' ) ) ), array( 'key' => 'field_package_excluded', 'label' => "What's excluded", 'name' => 'package_excluded', 'type' => 'repeater', 'layout' => 'table', 'button_label' => 'Add excluded item', 'sub_fields' => array( $text( 'field_package_excluded_item', 'item', 'Item' ) ) ),
        array( 'key' => 'field_package_gallery_tab', 'label' => 'Gallery', 'type' => 'tab' ), array( 'key' => 'field_package_gallery', 'label' => 'Visualise your journey', 'name' => 'package_gallery', 'type' => 'gallery', 'return_format' => 'id' ),
        array( 'key' => 'field_package_booking_tab', 'label' => 'Booking / Enquiry', 'type' => 'tab' ), array( 'key' => 'field_package_booking_description', 'label' => 'Booking card description', 'name' => 'package_booking_description', 'type' => 'textarea', 'rows' => 2 ), $text( 'field_package_whatsapp_message', 'package_whatsapp_message', 'WhatsApp message (optional)' ),
    ), 'location' => array( array( array( 'param' => 'page_template', 'operator' => '==', 'value' => 'page-package-detail.php' ) ) ), 'position' => 'normal', 'style' => 'default', 'active' => true ) );
}
add_action( 'acf/init', 'luxxo_register_package_detail_fields' );
